version: '3.1'

services:
  php:
    container_name: php8.0-chat
    build:
      context: ./php
      args:
        - http_proxy
        - HTTP_PROXY
        - https_proxy
        - HTTPS_PROXY
        - no_proxy
    volumes:
      - "../src:/var/www/html"
    restart: always
    environment:
      - TZ=Europe/Moscow
      - PHP_MEMORY_LIMIT=256M
      - PHP_POST_MAX_SIZE=8M
      - PHP_MAX_FILE_UPLOADS=20
      - PHP_UPLOAD_MAX_FILESIZE=2M
      - PHP_SESSION_SAVE_HANDLER=files
      - PHP_SESSION_SAVE_PATH="/tmp/session"
      - PHP_MAX_INPUT_VARS=1000
      - PHP_MAX_EXECUTION_TIME=0
      - PHP_DATE_TIMEZONE=Europe/Moscow
      - PHP_LOG_ERRORS=1
      - PHP_LOG_ERRORS_MAX_LEN=1024
      - PHP_XDEBUG_IDEKEY=diversantvlz
      - PHP_XDEBUG_DEFAULT_ENABLE=0
      - PHP_XDEBUG_REMOTE_ENABLE=1
      - PHP_XDEBUG_REMOTE_AUTOSTART=0
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=0
      - PHP_XDEBUG_PROFILER_ENABLE=0
      - PHP_XDEBUG_REMOTE_HOST=host.docker.internal

  nginx:
    container_name: nginx-chat
    restart: always
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "8083:80"
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/demo.local.template:/etc/nginx/conf.d/demo.local.template"
      - "../src:/var/www/html"
    environment:
      - NGINX_HOST=demo.local
      - NGINX_PORT=80
      - PHP_FPM_HOST=php8.0-chat
      - PHP_FPM_PORT=9000
      - TZ=Europe/Moscow
    # command подменит в шаблоне вхоста переменные на значения из заданных переменных окружения
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/demo.local.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mysql:
    container_name: mariadb-chat
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - "./database/data:/var/lib/database"
      - "./database:/docker-entrypoint-initdb.d/:rw"

  adminer:
    container_name: adminer-chat
    image: adminer
    restart: always
    ports:
      - "8085:8080"